export const FETCH_STUDENTS_SUCCESS = "FETCH_STUDENTS_SUCCESS";
export const FETCH_STUDENTS_FAILURE = "FETCH_STUDENTS_FAILURE";
export const FETCH_ALL_NATIONALITY_SUCCESS = "FETCH_ALL_NATIONALITY_SUCCESS";
export const FETCH_ALL_NATIONALITY_FAILURE = "FETCH_ALL_NATIONALITY_FAILURE";
export const FETCH_STUDENT_NATIONALITY_SUCCESS =
  "FETCH_STUDENT_NATIONALITY_SUCCESS";
export const FETCH_STUDENT_NATIONALITY_FAILURE =
  "FETCH_STUDENT_NATIONALITY_FAILURE";
export const ADD_FAMILY_MEMBER = "ADD_FAMILY_MEMBER";
export const UPDATE_FAMILY_MEMBER = "UPDATE_FAMILY_MEMBER";
export const DELETE_FAMILY_MEMBER = "DELETE_FAMILY_MEMBER";
export const DELETE_USER = "DELETE_USER";
export const ADD_USER_NATIONALITY = "ADD_USER_NATIONALITY";
export const POST_STUDENT_REQUEST = "POST_STUDENT_REQUEST";
export const POST_STUDENT_SUCCESS = "POST_STUDENT_SUCCESS";
export const POST_STUDENT_FAILURE = "POST_STUDENT_FAILURE";
export const FETCH_FAMILY_DATA_SUCCESS = "FETCH_FAMILY_DATA_SUCCESS";
export const FETCH_FAMILY_DATA_FAILURE = "FETCH_FAMILY_DATA_FAILURE";
export const POST_STUDENT_FAMILY_REQUEST = "POST_STUDENT_FAMILY_REQUEST";
export const POST_STUDENT_FAMILY_SUCCESS = "POST_STUDENT_FAMILY_SUCCESS";
export const POST_STUDENT_FAMILY_FAILURE = "POST_STUDENT_FAMILY_FAILURE";
export const ADD_STUDENT_FAMILY_NATIONALITY = "ADD_STUDENT_FAMILY_NATIONALITY";
export const UPDATE_STUDENT_DATA = "UPDATE_STUDENT_DATA";
export const UPDATE_STUDENT_NATIONALITY = "UPDATE_STUDENT_NATIONALITY";
export const SET_ADMIN_ROLE = "SET_ADMIN_ROLE";
export const SET_REGISTRAR_ROLE = "SET_REGISTRAR_ROLE";
